services:
  quotes-service:
    build: ./quotes-service
    networks:
      - quote-net

  backend:
    build: ./backend
    container_name: quote-backend
    ports:
      - "4000:3000"
    environment:
      QUOTES_SERVICE_HOST: http://quotes-service:3005
    depends_on:
      - quotes-service
    networks:
      - quote-net  

networks:
  quote-net:
    external: true 